# Generated by Django 5.1.7 on 2025-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_entry_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='entry',
        ),
    ]
